oauth2-proxy:
  config:
    existingSecret: oauth2-proxy-secret

    configFile: |-
      reverse_proxy = true
      email_domains = [ "*" ]
      upstreams = [ "static://202" ]
      provider = "github"
      scope = "user:email"
      github_users = "BlueNc"
      cookie_domains = ".codeblue.ovh"
      redirect_url = "https://auth.codeblue.ovh/oauth2/callback"
      whitelist_domains = "*.codeblue.ovh"

  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - auth.codeblue.ovh
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
      traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd,default-auth-headers@kubernetescrd
    tls:
      - hosts:
          - auth.codeblue.ovh
        secretName: auth-codeblue-ovh

  redis:
    enabled: false
