global:
  domain: argo-cd.codeblue.ovh

argo-cd:
  fullnameOverride: "argocd"
  namespace: argocd
  configs:
    params:
      server.insecure: true
  crds:
    install: true
    keep: false
  dex:
    enabled: false
  server:
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt"
        # traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd,default-oauth2-proxy-redirect@kubernetescrd,default-oauth2-proxy-forward@kubernetescrd
      tls: true
      https: false
  certificate:
    enabled: false
