ingress:
  enabled: true
  pathType: Prefix
  ingressClassName: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
  path: /
  tls:
    - hosts:
        - chat.bluenc.ovh
      secretName: chat-bluenc-ovh
