apiVersion: apps/v1
kind: Deployment
metadata:
  name: magali
spec:
  selector:
    matchLabels:
      app: magali
  template:
    metadata:
      labels:
        app: magali
    spec:
      containers:
      - name: magali
        image: benbusby/whoogle-search
        imagePullPolicy: Always
        ports:
          - containerPort: 5000