---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: google-client
spec:
  encryptedData:
    client-secret: AgCt0QwKethdpU9ZSX9U0M7Jhp2I3XrA5wztFak7IghDwUMNIifHdozJGNd11DL2ZmVyH6WPKXnMMDm7G66TnBxlx+QgEc/146+KUkEtAc7UlM2+orY+UZXfA9+1IFmtUu/6OvVLrYE8SNYSyjFFZXdrOYnPzkQvu07F1QCMF0HLVlIwS6mxQl6sKEZHdUmsZF7x9+vBEVDfacz/C+0Rr9G0FgTSn9D7FwaVeveZ8kBfCC6yqtXlIrzxdgUGHjNsjHGbvTjoHJoOxWwtvSfU72AH8/qE9GtXL2b4E89Z6BhTh0p3VRrAIlEw6972FaMj5NaEVK82U68vcS0AgBjyHcp4cQA2sHHAhW6LF63eknGesoedKCxBe7bY+WVtLy9hlrGFctH9w6Tu6a4IbxbNRlZPGdUdxbY3DUe7IP1h32437zg7Tsna/DdDBN47TFJv/rilkIfynkjowWwjgrvosTNhasj2+RBY6pjPrtlgS4QblcTc3+euF3lDMwTzUYqcLtPpIlDqQJaaqnQYAXEfg/mLmpgVpsZvtVrfdcxRoXxcAzRCl0Ly0MjUp00gsClnpAkbcFPWpFJ2euP4OIWTZROilSAzxgO3GsFCMg6UpxRhvy/Hx0bnpDT1QOIFTP6cZP8SQY/WtNXPQcc/hDVbYtow4E7St4DCqNnVvpCrfz37PyKeoUhx6hSptbK/kPL8IKgUgp1JzKsZvDAQ/TPBRtgdTMxHbvQsBM5Pa+oXOvqUTKYV6A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: google-client
