apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: server
    spec:
      containers:
        - args:
            - --host=0.0.0.0
            - --port=42110
            - -vv
            - --anonymous-mode
            - --non-interactive
          env:
            - name: KHOJ_ADMIN_EMAIL
              value: username@example.com
            - name: KHOJ_ADMIN_PASSWORD
              value: password
            - name: KHOJ_DEBUG
              value: "True"
            - name: KHOJ_DJANGO_SECRET_KEY
              value: secret
            - name: KHOJ_SEARXNG_URL
              value: http://search:8080
            - name: KHOJ_TERRARIUM_URL
              value: http://sandbox:8080
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_HOST
              value: database
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: postgres
          image: ghcr.io/khoj-ai/khoj:latest
          name: server
          ports:
            - containerPort: 42110
              protocol: TCP
          volumeMounts:
            - mountPath: /root/.khoj
              name: khoj
            - mountPath: /root/.cache/torch/sentence_transformers
              name: khoj
            - mountPath: /root/.cache/huggingface
              name: khoj
          workingDir: /app
      restartPolicy: Always
      volumes:
        - name: khoj
          persistentVolumeClaim:
            claimName: khoj
