apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: khoj
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: khoj
    server: https://kubernetes.default.svc
  project: argocd
  source:
    path: khoj
    repoURL: https://github.com/BlueNc/vke-fch.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
