apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: argocd
  source:
    repoURL: https://traefik.github.io/charts
    targetRevision: 31.1.0
    chart: traefik
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/BlueNc/vke-fch/main/traefik/values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true