kind: ConfigMap
apiVersion: v1
metadata:
  name: code-server-config
data:
  config.yaml: |-
    bind-addr: 127.0.0.1:8080
    auth: password
    hashed-password: a17f3992aa01c0b4899908049be7983a569d21ec0294c8ab7669663f9a6a10c3
    cert: false